import type { VenueMaster } from "../storage/types";
import type { VenueSeedRecord } from "./types";

export const VENUE_SEED_DATA: readonly VenueSeedRecord[] = [
  {
    area: "AI/ML",
    venueId: "neurips",
    canonicalName: "Advances in Neural Information Processing Systems",
    shortName: "NeurIPS",
    aliases: ["Neural Information Processing Systems", "NIPS", "NeurIPS"],
    type: "conference",
    ccfRank: "A",
    coreRank: "A*",
  },
  {
    area: "AI/ML",
    venueId: "icml",
    canonicalName: "International Conference on Machine Learning",
    shortName: "ICML",
    aliases: ["ICML"],
    type: "conference",
    ccfRank: "A",
    coreRank: "A*",
  },
  {
    area: "AI/ML",
    venueId: "iclr",
    canonicalName: "International Conference on Learning Representations",
    shortName: "ICLR",
    aliases: ["ICLR"],
    type: "conference",
    ccfRank: "A",
    coreRank: "A*",
  },
  {
    area: "NLP",
    venueId: "acl",
    canonicalName:
      "Annual Meeting of the Association for Computational Linguistics",
    shortName: "ACL",
    aliases: [
      "Association for Computational Linguistics",
      "Meeting of the Association for Computational Linguistics",
      "ACL",
    ],
    type: "conference",
    ccfRank: "A",
    coreRank: "A*",
  },
  {
    area: "NLP",
    venueId: "emnlp",
    canonicalName:
      "Conference on Empirical Methods in Natural Language Processing",
    shortName: "EMNLP",
    aliases: ["Empirical Methods in Natural Language Processing", "EMNLP"],
    type: "conference",
    ccfRank: "B",
    coreRank: "A*",
  },
  {
    area: "NLP",
    venueId: "naacl",
    canonicalName:
      "Conference of the North American Chapter of the Association for Computational Linguistics",
    shortName: "NAACL",
    aliases: [
      "North American Chapter of the Association for Computational Linguistics",
      "NAACL",
    ],
    type: "conference",
    ccfRank: "B",
    coreRank: "A*",
  },
  {
    area: "CV",
    venueId: "cvpr",
    canonicalName:
      "IEEE/CVF Conference on Computer Vision and Pattern Recognition",
    shortName: "CVPR",
    aliases: ["Conference on Computer Vision and Pattern Recognition", "CVPR"],
    type: "conference",
    ccfRank: "A",
    coreRank: "A*",
  },
  {
    area: "CV",
    venueId: "iccv",
    canonicalName: "IEEE International Conference on Computer Vision",
    shortName: "ICCV",
    aliases: ["International Conference on Computer Vision", "ICCV"],
    type: "conference",
    ccfRank: "A",
    coreRank: "A*",
  },
  {
    area: "CV",
    venueId: "eccv",
    canonicalName: "European Conference on Computer Vision",
    shortName: "ECCV",
    aliases: ["ECCV"],
    type: "conference",
    ccfRank: "B",
    coreRank: "A*",
  },
  {
    area: "RecSys",
    venueId: "recsys",
    canonicalName: "ACM Conference on Recommender Systems",
    shortName: "RecSys",
    aliases: ["Conference on Recommender Systems", "ACM RecSys", "RecSys"],
    type: "conference",
    ccfRank: "B",
    coreRank: "A",
  },
  {
    area: "Security",
    venueId: "sp",
    canonicalName: "IEEE Symposium on Security and Privacy",
    shortName: "S&P",
    aliases: ["Security and Privacy", "IEEE Security and Privacy", "Oakland"],
    type: "conference",
    ccfRank: "A",
    coreRank: "A*",
  },
  {
    area: "Security",
    venueId: "usenix-security",
    canonicalName: "USENIX Security Symposium",
    shortName: "USENIX Security",
    aliases: ["USENIX Security", "USENIX Security Symposium"],
    type: "conference",
    ccfRank: "A",
    coreRank: "A*",
  },
  {
    area: "Security",
    venueId: "ccs",
    canonicalName: "ACM Conference on Computer and Communications Security",
    shortName: "CCS",
    aliases: ["Computer and Communications Security", "ACM CCS", "CCS"],
    type: "conference",
    ccfRank: "A",
    coreRank: "A*",
  },
  {
    area: "DB",
    venueId: "sigmod",
    canonicalName: "ACM International Conference on Management of Data",
    shortName: "SIGMOD",
    aliases: [
      "ACM SIGMOD International Conference on Management of Data",
      "SIGMOD Conference",
      "SIGMOD",
    ],
    type: "conference",
    ccfRank: "A",
    coreRank: "A*",
  },
  {
    area: "DB",
    venueId: "pvldb",
    canonicalName: "Proceedings of the VLDB Endowment",
    shortName: "PVLDB",
    aliases: ["VLDB Endowment", "Proceedings of the VLDB Endowment", "PVLDB"],
    type: "journal",
    ccfRank: "A",
    coreRank: "A*",
  },
  {
    area: "DB",
    venueId: "icde",
    canonicalName: "IEEE International Conference on Data Engineering",
    shortName: "ICDE",
    aliases: ["International Conference on Data Engineering", "ICDE"],
    type: "conference",
    ccfRank: "A",
    coreRank: "A*",
  },
  {
    area: "SE",
    venueId: "icse",
    canonicalName: "International Conference on Software Engineering",
    shortName: "ICSE",
    aliases: ["ICSE"],
    type: "conference",
    ccfRank: "A",
    coreRank: "A*",
  },
  {
    area: "SE",
    venueId: "fse",
    canonicalName:
      "ACM Joint European Software Engineering Conference and Symposium on the Foundations of Software Engineering",
    shortName: "FSE",
    aliases: ["Foundations of Software Engineering", "ESEC/FSE", "FSE"],
    type: "conference",
    ccfRank: "A",
    coreRank: "A*",
  },
  {
    area: "SE",
    venueId: "ase",
    canonicalName:
      "IEEE/ACM International Conference on Automated Software Engineering",
    shortName: "ASE",
    aliases: ["Automated Software Engineering", "ASE"],
    type: "conference",
    ccfRank: "A",
    coreRank: "A",
  },
  {
    area: "HCI",
    venueId: "chi",
    canonicalName: "ACM Conference on Human Factors in Computing Systems",
    shortName: "CHI",
    aliases: ["Human Factors in Computing Systems", "CHI"],
    type: "conference",
    ccfRank: "A",
    coreRank: "A*",
  },
  {
    area: "HCI",
    venueId: "uist",
    canonicalName: "ACM Symposium on User Interface Software and Technology",
    shortName: "UIST",
    aliases: ["User Interface Software and Technology", "UIST"],
    type: "conference",
    ccfRank: "A",
    coreRank: "A*",
  },
  {
    area: "HCI",
    venueId: "cscw",
    canonicalName:
      "ACM Conference on Computer-Supported Cooperative Work and Social Computing",
    shortName: "CSCW",
    aliases: [
      "Computer-Supported Cooperative Work and Social Computing",
      "Computer Supported Cooperative Work",
      "CSCW",
    ],
    type: "conference",
    ccfRank: "A",
    coreRank: "A",
  },
] as const;

export function getSeedVenueMasters(): VenueMaster[] {
  return VENUE_SEED_DATA.map((venue) => ({
    venueId: venue.venueId,
    canonicalName: venue.canonicalName,
    shortName: venue.shortName,
    type: venue.type,
    ccfRank: venue.ccfRank ?? "",
    coreRank: venue.coreRank ?? "",
    aliasesJson: [...venue.aliases],
    updatedAt: 0,
  }));
}
